### ISSUE TITLE
1.1.3 crash on launch (new AxeItemMixin might be the cause) 

### ISSUE THREAD

**Issue by cobbdzon** [uTa4u/TFC-Woodworking#4]
Ever since I updated from 1.1.2 to 1.1.3 since I had the same issue as #3. But I ran into a problem where the server refused to open because of the new update. Hopefully the logs below can give context to the issue.

## Full Log
```
[32m[12:14:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.3.12, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[m[32m[12:14:08] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 22.0.1 by Oracle Corporation; OS Linux arch amd64 version 6.1.0-21-amd64
[m[32m[12:14:09] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[m[32m[12:14:09] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/mcserver/terrafirma/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[m[32m[12:14:09] [main/INFO] [AutoModpack/]: Prelaunching AutoModpack...
[m[32m[12:14:09] [main/INFO] [AutoModpack/]: Loaded config! took 39ms
[m[32m[12:14:09] [main/INFO] [AutoModpack/]: AutoModpack self-updater is disabled in server config.
[m[32m[12:14:09] [main/INFO] [AutoModpack/]: AutoModpack prelaunched! took 47ms
[m[33m[12:14:10] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/mcserver/terrafirma/libraries/net/minecraftforge/fmlcore/1.20.1-47.3.12/fmlcore-1.20.1-47.3.12.jar is missing mods.toml file
[m[33m[12:14:10] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/mcserver/terrafirma/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.3.12/javafmllanguage-1.20.1-47.3.12.jar is missing mods.toml file
[m[33m[12:14:10] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/mcserver/terrafirma/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.3.12/lowcodelanguage-1.20.1-47.3.12.jar is missing mods.toml file
[m[33m[12:14:10] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/mcserver/terrafirma/libraries/net/minecraftforge/mclanguage/1.20.1-47.3.12/mclanguage-1.20.1-47.3.12.jar is missing mods.toml file
[m[33m[12:14:10] [main/WARN] [ne.mi.ja.se.JarSelector/]: Attempted to select two dependency jars from JarJar which have the same identification: Mod File:  and Mod File: . Using Mod File: 
[m[32m[12:14:10] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 10 dependencies adding them to mods collection
[m[32m[12:14:13] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[m[32m[12:14:13] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[m[32m[12:14:13] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments []
[m[1;31m[12:14:13] [main/ERROR] [mixin/]: Failed reading REFMAP JSON from tfcwoodwork.refmap.json: java.lang.NullPointerException Cannot invoke "org.spongepowered.asm.mixin.refmap.ReferenceMapper.setResourceName(String)" because "mapper" is null
[m[33m[12:14:13] [main/WARN] [mixin/]: Reference map 'tfcwoodwork.refmap.json' for tfcwoodwork.mixins.json could not be read. If this is a development environment you can ignore this message
[m[32m[12:14:13] [main/INFO] [Canary/]: Loaded configuration file for Canary: 116 options available, 0 override(s) found
[m[33m[12:14:13] [main/WARN] [mixin/]: Reference map 'coroutil.refmap.json' for coroutil.mixins.json could not be read. If this is a development environment you can ignore this message
[m[33m[12:14:13] [main/WARN] [mixin/]: Reference map 'packetfixer-forge-forge-refmap.json' for packetfixer-forge.mixins.json could not be read. If this is a development environment you can ignore this message
[m[33m[12:14:13] [main/WARN] [mixin/]: Error loading class: net/fabricmc/fabric/impl/networking/server/ServerLoginNetworkAddon (java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.networking.server.ServerLoginNetworkAddon)
[m[33m[12:14:14] [main/WARN] [mixin/]: Error loading class: net/minecraft/world/entity/vehicle/AbstractBoat (java.lang.ClassNotFoundException: net.minecraft.world.entity.vehicle.AbstractBoat)
[m[33m[12:14:14] [main/WARN] [mixin/]: Error loading class: loaderCommon/forge/com/seibel/distanthorizons/common/wrappers/worldGeneration/mimicObject/ChunkLoader (java.lang.ClassNotFoundException: loaderCommon.forge.com.seibel.distanthorizons.common.wrappers.worldGeneration.mimicObject.ChunkLoader)
[m[32m[12:14:15] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[m[32m[12:14:18] [main/INFO] [mixin/]: Instancing error handler class com.illusivesoulworks.polymorph.mixin.IntegratedMixinPlugin
[m[1;31m[12:14:18] [main/FATAL] [mixin/]: Mixin apply failed tfcwoodwork.mixins.json:AxeItemMixin -> net.minecraft.world.item.AxeItem: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyVariable annotation on useOn could not find any targets matching 'useOn' in net.minecraft.world.item.AxeItem. No refMap loaded. [PREINJECT Applicator Phase -> tfcwoodwork.mixins.json:AxeItemMixin -> Prepare Injections ->  -> localvar$zfi000$useOn(Ljava/util/Optional;)Ljava/util/Optional; -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyVariable annotation on useOn could not find any targets matching 'useOn' in net.minecraft.world.item.AxeItem. No refMap loaded. [PREINJECT Applicator Phase -> tfcwoodwork.mixins.json:AxeItemMixin -> Prepare Injections ->  -> localvar$zfi000$useOn(Ljava/util/Optional;)Ljava/util/Optional; -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo.<init>(ModifyVariableInjectionInfo.java:45) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1311) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar%2365!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar%2355!/:10.0.9+10.0.9+main.dcd20f30] {}
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at net.minecraft.world.level.block.ComposterBlock.m_51988_(ComposterBlock.java:60) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?] {re:classloading}
	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:47) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:121) ~[server-1.20.1-20230612.114412-srg.jar%23266!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.12.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.3.12.jar%2369!/:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.3.12.jar%2369!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
[m
```

## Mod List
exclude those commented
```yaml
modlist_name: "terrafirma"

minecraft_version: "1.20.1"
mod_loader: "forge"

client:
 - embeddium
 - oculus
 - ihearttfc
 - dynamic-fps
 # - fast-items
 # - collision-fix
 - cull-leaves
 - badoptimizations
 - fast-ip-ping
 - better-ping-display
 - bbrb

 - travelers-titles
 - true-darkness-forge-updated-fork
 - tfc-vessel-tooltip

 - item-highlighter
 - cubes-without-borders
 - seamless-loading-screen
 - rrls
 - commandkeys
 - just-zoom
 - resourcepackcached

 - camera-overhaul-reforged
 - fog
 - explosive-enhancement-forge
 - enhancedvisuals
 - lucent
 - first-person-model
 - visuality-forge
 - make_bubbles_pop
 - tiny-item-animations
 - chat-heads
 - emoji-type
 - not-enough-animations
 - better-third-person
 - modelfix
 - ambient-environment
 - chunkanimator

 # sound
 - sound
 - sound-physics-remastered
 - ambientsounds
 # - delayed-thunder

 - yacl

shared:
 - automodpack
 - better-combat
 - jei
 - curios
 
 # terrafirmacraft
 - terrafirmacraft
 - firmaciv
 - sacks-n-such
 
 # farmers delight support
 - farmers-delight
 - farmers-delight-tfc
 # create support
 - create
 - wooden-cog
 
 - tfc-weather
 - tfc-regrowing-forests
 - terrafly
 - knights-of-terrafirma
 - water-flasks
 - roads-and-roofs-tfc
 - tfc-astikor-carts
 - tfc-ambiental-second-edition
 - barrels-2012
 - tfc-woodworking
 - tfc-caelum
 
 - immersive-snow
 - zombie-awareness
 - polymorph
 - multiplayer-server-pause
 - this-boat-is-mine
 - better-boat-movement
 - carry-on
 - xaeros-world-map
 - corpse
 - itemphysic
 - crawl-on-demand
 - horseman
 - swimming-horses-forge
 
 # modpack configuration
 - kubejs
 - kubejs-tfc

 # performance
 - entityculling
 - ferrite-core
 - packet-fixer
 - canary
 - starlight-forge
 - mobtimizations
 - notenoughcrashes
 - attributefix

 # social
 - no-player-nametags
 - what-are-they-up-to
 - simple-voice-chat
 - emotecraft
 - wthit
 - female-gender

 # fabric
 # - forgified-fabric-api
 # - connector

 # - fabrictailor

server:
 - chunky
 - noisium
 - sparsestructuresreforged
 - fastback
 - spark
 - discord-statusbot
 - icterine
 - lmd
 - adaptive-performance-tweaks-player
 - skinrestorer
```

**Comment by PermskyKit** [comment]
Um, did you just remove the ability to create canoes again? I'm trying the latest version and... Nothing happens..

**Comment by uTa4u** [comment]
As for the original issue - it was fixed in 1.1.4. It was indeed a mixin skill issue on my side.
